WIP: VZ-1315
verrazzano/verrazzano-cluster-operator pull request #32
Opened 2020-10-21 17:09 UTC by guoyongzhang

2020-10-27 18:07 UTC, markxnelson requested changes

2020-10-27 18:07 UTC, markxnelson commented on go.mod
> +	github.com/rs/zerolog v1.19.0
you need an approval to change a dep version

2020-10-28 17:58 UTC, shihchang commented on go.mod
> +	github.com/rs/zerolog v1.19.0
reverted to the approved v1.19.0

2020-10-28 20:54 UTC, desagar commented on pkg/util/logs/logs.go
> +	log.Logger = zerolog.New(os.Stderr).With().Caller().Timestamp().Logger()
So this globally sets the logger? Does that mean the timestamp is calculated up front when you create this logger, or every time there is a call to log.Info or log.Debug etc?

2020-10-28 20:59 UTC, desagar commented on pkg/util/logs/logs.go
> +	log.Logger = zerolog.New(os.Stderr).With().Caller().Timestamp().Logger()
Couple more comments - 
* We discussed adding a component field to the logger globally for each component (i.e.) "verrazzano-cluster-operator" in this case. I think that would be nice to have.
* Also, instead of globally setting the logger on zerolog I think it would be nicer to create this Logger, store it as a global variable and use that variable everywhere (maybe with a GetLogger() or something)
* Did you verify whether multi-threaded usage on a single logger is ok in zerolog?

2020-10-28 20:59 UTC, desagar commented on pkg/rancher/rancher.go
> +	log.Debug().Msgf("[APICall] [%s] url:'%s'", httpMethod, rancherConfig.URL+apiPath)
I wonder why this was set to Info before

2020-10-28 21:01 UTC, desagar commented on deploy/operator.yaml
> -          - --v=4
why did you choose to change this to an env var? 

I don't have a particular preference, other than, if we use a flag it's possible to change it by restarting the process inside the container without having to restart the container - not sure if we need this, but I'm curious why you chose to change this.

2020-10-28 22:58 UTC, guoyongzhang commented on pkg/util/logs/logs.go
> +	log.Logger = zerolog.New(os.Stderr).With().Caller().Timestamp().Logger()
log.logger is the global logger.
.Timestamp() simply means this logger will include a "time" field every time it logs something.

2020-10-28 23:02 UTC, guoyongzhang commented on pkg/util/logs/logs.go
> +	log.Logger = zerolog.New(os.Stderr).With().Caller().Timestamp().Logger()
filebeat will include a field to identify the pod.  it is debatable if we want to include a reductant component field in the log message.  the pro is that the log message is independent of the collection mechanism.
log.Logger is already a well-known global variable.  why re-invent another variable or function?

2020-10-28 23:07 UTC, guoyongzhang commented on deploy/operator.yaml
> -          - --v=4
It was a leftover from Davis' commit.  Now --v doesn't mean anything, it should be deleted.  
Davis did introduce an env var "LOG_LEVEL", which is not used helm chart or documented anywhere.

2020-10-29 01:16 UTC, shihchang commented on pkg/util/logs/logs.go
> +	log.Logger = zerolog.New(os.Stderr).With().Caller().Timestamp().Logger()
Yes, this log.Logger will be used by all the log.Debug(), log.Info(), and log.Warn() calls

2020-10-29 01:18 UTC, shihchang commented on pkg/rancher/rancher.go
> +	log.Debug().Msgf("[APICall] [%s] url:'%s'", httpMethod, rancherConfig.URL+apiPath)
all the glog.V(7) and glog.V(6) (level>=6) are changed to log.Debug()(level=debug)

2020-10-29 01:27 UTC, shihchang commented on pkg/util/logs/logs.go
> +	log.Logger = zerolog.New(os.Stderr).With().Caller().Timestamp().Logger()
* We already have kubernetes.container.name=verrazzano-cluster-operator" and kubernetes.labels.app=verrazzano-cluster-operator". That "Caller" also adds log.caller=<path>/verrazzano-cluster-operator/pkg/controller/controller.go:<line#>. The component field may not be needed.
* GetLogger() will need to be defined in every package; otherwise utiPackage.GetLogger().Info() is not any better than log.Info().
* Changed to zerolog.SyncWriter(os.Stderr) as os.Stderr may not be thread safe.

2020-10-29 01:30 UTC, shihchang commented on deploy/operator.yaml
> -          - --v=4
The "--v=4" arg is targeting github.com/golang/glog which has been completely removed. If we leave --v=4, the operator will fail in starting up complaining the unknown argument.

2020-10-29 13:19 UTC, bobdonat commented on deploy/operator.yaml
> -          - --v=4
So how would I change the log level with the new logging.  With the old logging I could edit the deployment and change the --v argument.  I think we should not be regressing when it comes to being able to change the log level.

2020-11-02 16:45 UTC, gilbode commented
@shihchang - can you post a snippet of what these logs look like?

2020-11-02 16:54 UTC, shihchang commented
> @shihchang - can you post a snippet of what these logs look like?

{"level":"info","time":"2020-11-02T11:49:26-05:00","caller":"logs/logs_test.go:72","message":"hello"}

on kibana, there are fields of log.level, log.message, log.time, log.caller those can be used for filtering/searching

2020-11-02 16:57 UTC, shihchang commented on deploy/operator.yaml
> -          - --v=4
The verbosityLevel (--v) is converted to logLevel as --v=4 equals info level.

2020-11-02 16:57 UTC, gilbode commented on pkg/util/logs/logs.go
> +	logger, _ := config.Build()
This is ignoring any errors - they need to be handled.

2020-11-02 17:01 UTC, gilbode commented
@shihchang - did you create an elasticsearch mapping template as per https://jira.oraclecorp.com/jira/browse/VZ-1315 or are you letting elasticsearch automatically create the mapping?  probably the mapping template needs to be created by filebeat or whoever is shipping the logs.

2020-11-02 17:23 UTC, shihchang commented
> @shihchang - did you create an elasticsearch mapping template ...

No, but the mapping was created by filebeat sending the json docs to elasticsearch to index. filebeat is configured in verrazzano-operator to parse the content of the "message" field as json and add the fields of  log.level, log.message, log.time, log.caller

```
filebeat.inputs:
- type: docker
  containers.ids:
  - "*"
  processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: ""
      overwrite_keys: true
  - rename:
      fields:
       - from: "level"
         to: "log.level"
       - from: "time"
         to: "log.time"
       - from: "caller"
         to: "log.caller"
       - from: "message"
         to: "log.message"
      ignore_missing: false
      fail_on_error: true
  - add_kubernetes_metadata:
      in_cluster: true
```

2020-11-02 17:31 UTC, shihchang commented on pkg/util/logs/logs.go
> +	logger, _ := config.Build()
fixed

2020-11-02 17:34 UTC, bobdonat commented on cmd/main.go
> +	verboseFlag := flag.Lookup("v") //--v might have been defined in glog in transitive dependencies
I think we should use the zap built in flags for logging instead of --v, which is glog thing.

This code sets up the zap logging flags and then passed to zap to set log level and other logging flags.
	opts := zap.Options{}
	opts.BindFlags(flag.CommandLine)

2020-11-02 18:19 UTC, desagar commented on pkg/util/logs/logs.go
> +	logger, err := config.Build()
where is this "logger" variable used?

2020-11-02 18:19 UTC, desagar commented on pkg/util/logs/logs.go
> +	logger, err := config.Build()
Oh I see below it's passed to zap.ReplaceGlobals - so we are setting a global logger? Is this the recommended way to do things in zap?

2020-11-02 18:25 UTC, desagar commented on pkg/util/logs/logs_test.go
> +	err := zap.L().Sync()
When reading InitLogs, I expected that a test might verify that the config settings are as expected - of course, I don't know if that's possible to do. But it's not clear to me what is being tested here.

2020-11-02 18:29 UTC, pfmackin commented on Jenkinsfile
> -        disableConcurrentBuilds()
Why is this part of the structured logging commit?

2020-11-02 18:51 UTC, shihchang commented on pkg/util/logs/logs.go
> +	logger, err := config.Build()
zap.ReplaceGlobals(logger) sets this logger as global logger, it can be used as zap.S(), sugared with template/format log, or zap.L(), logger.

2020-11-02 18:56 UTC, shihchang commented on cmd/main.go
> +	verboseFlag := flag.Lookup("v") //--v might have been defined in glog in transitive dependencies
The zap.Options comes from "sigs.k8s.io/controller-runtime/pkg/log/zap"; it is NOT from "go.uber.org/zap". The --zap-log-level and other options are defined in controller-runtime, not zap. Do we want to add controller-runtime as dependency in order to use the options?

2020-11-02 18:57 UTC, desagar commented on Jenkinsfile
> -        disableConcurrentBuilds()
I'll hazard a guess and say that Chen got tired of waiting for builds on his branch to start, until a previous build completed. I've been annoyed at the same thing. There's no reason to disable concurrent builds here.

2020-11-02 19:07 UTC, bobdonat commented on cmd/main.go
> +	verboseFlag := flag.Lookup("v") //--v might have been defined in glog in transitive dependencies
Not sure.  In the generated operator cases we already have a dependency on the controller-runtime.

2020-11-02 19:09 UTC, desagar commented
> > @shihchang - did you create an elasticsearch mapping template ...
> 
> No, but the mapping was created by filebeat sending the json docs to elasticsearch to index. filebeat is configured in verrazzano-operator to parse the content of the "message" field as json and add the fields of log.level, log.message, log.time, log.caller

So as I understand the docs for decode_json_fields, this still means the elasticsearch mapping is auto-created. I know you were researching how to make sure the fields are always interpreted as strings (except for log.time of course), but I didn't know what conclusion you had come to based on that.

2020-11-02 19:23 UTC, shihchang commented on Jenkinsfile
> -        disableConcurrentBuilds()
don't know, this branch was from Davis long ago. Reverted.

2020-11-02 23:08 UTC, shihchang commented on pkg/util/logs/logs_test.go
> +	err := zap.L().Sync()
fixed to verify the log-level work as expected

2020-11-04 01:56 UTC, shihchang commented on deploy/operator.yaml
> -          - --v=4
The  --v is removed and replaced to --zap-log-level (default --zap-log-level=info).

2020-11-04 01:56 UTC, shihchang commented on cmd/main.go
> +	verboseFlag := flag.Lookup("v") //--v might have been defined in glog in transitive dependencies
The  --v is removed and replaced to --zap-log-level (default --zap-log-level=info).

2020-11-05 14:38 UTC, shihchang approved these changes

2020-11-05 14:49 UTC, markxnelson approved these changes
LGTM

2020-11-05 14:51 UTC, merged